<?php
namespace App\OpenApi\Paths;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/budget-types', operationId: 'list_budget_types', summary: 'List Budget Types', description: 'Requires budget_type_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/budget-types', operationId: 'create_budget_types', summary: 'Create Budget Types', description: 'Requires budget_type_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/budget-types/{budget_type}', operationId: 'update_budget_types', summary: 'Update Budget Types', description: 'Requires budget_type_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'budget_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/budget-types/{budget_type}', operationId: 'delete_budget_types', summary: 'Delete Budget Types', description: 'Requires budget_type_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'budget_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/budgets', operationId: 'list_budgets', summary: 'List Budgets', description: 'Requires budget_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/budgets', operationId: 'create_budgets', summary: 'Create Budgets', description: 'Requires budget_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/budgets/{budget}', operationId: 'update_budgets', summary: 'Update Budgets', description: 'Requires budget_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'budget', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/budgets/{budget}', operationId: 'delete_budgets', summary: 'Delete Budgets', description: 'Requires budget_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'budget', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/expense-targets', operationId: 'list_expense_targets', summary: 'List Expense Targets', description: 'Requires expense_target_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/expense-targets', operationId: 'create_expense_targets', summary: 'Create Expense Targets', description: 'Requires expense_target_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/expense-targets/{expense_target}', operationId: 'update_expense_targets', summary: 'Update Expense Targets', description: 'Requires expense_target_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense_target', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/expense-targets/{expense_target}', operationId: 'delete_expense_targets', summary: 'Delete Expense Targets', description: 'Requires expense_target_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense_target', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/expense-types', operationId: 'list_expense_types', summary: 'List Expense Types', description: 'Requires expense_type_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/expense-types', operationId: 'create_expense_types', summary: 'Create Expense Types', description: 'Requires expense_type_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/expense-types/{expense_type}', operationId: 'update_expense_types', summary: 'Update Expense Types', description: 'Requires expense_type_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/expense-types/{expense_type}', operationId: 'delete_expense_types', summary: 'Delete Expense Types', description: 'Requires expense_type_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/expenses', operationId: 'list_expenses', summary: 'List Expenses', description: 'Requires expense_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/expenses', operationId: 'create_expenses', summary: 'Create Expenses', description: 'Requires expense_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/expenses/{expense}', operationId: 'update_expenses', summary: 'Update Expenses', description: 'Requires expense_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/expenses/{expense}', operationId: 'delete_expenses', summary: 'Delete Expenses', description: 'Requires expense_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/banks', operationId: 'list_banks', summary: 'List Banks', description: 'Requires bank_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/banks', operationId: 'create_banks', summary: 'Create Banks', description: 'Requires bank_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/banks/{bank}', operationId: 'update_banks', summary: 'Update Banks', description: 'Requires bank_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'bank', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/banks/{bank}', operationId: 'delete_banks', summary: 'Delete Banks', description: 'Requires bank_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'bank', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/saving-types', operationId: 'list_saving_types', summary: 'List Saving Types', description: 'Requires saving_type_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/saving-types', operationId: 'create_saving_types', summary: 'Create Saving Types', description: 'Requires saving_type_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/saving-types/{saving_type}', operationId: 'update_saving_types', summary: 'Update Saving Types', description: 'Requires saving_type_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'saving_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/saving-types/{saving_type}', operationId: 'delete_saving_types', summary: 'Delete Saving Types', description: 'Requires saving_type_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'saving_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/savings', operationId: 'list_savings', summary: 'List Savings', description: 'Requires saving_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/savings', operationId: 'create_savings', summary: 'Create Savings', description: 'Requires saving_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/savings/{saving}', operationId: 'update_savings', summary: 'Update Savings', description: 'Requires saving_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'saving', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/savings/{saving}', operationId: 'delete_savings', summary: 'Delete Savings', description: 'Requires saving_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'saving', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/withdraws', operationId: 'list_withdraws', summary: 'List Withdraws', description: 'Requires withdraw_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/withdraws', operationId: 'create_withdraws', summary: 'Create Withdraws', description: 'Requires withdraw_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/withdraws/{withdraw}', operationId: 'update_withdraws', summary: 'Update Withdraws', description: 'Requires withdraw_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'withdraw', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/withdraws/{withdraw}', operationId: 'delete_withdraws', summary: 'Delete Withdraws', description: 'Requires withdraw_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'withdraw', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/goals', operationId: 'list_goals', summary: 'List Goals', description: 'Requires goal_list permission.', tags: ['Finance'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/goals', operationId: 'create_goals', summary: 'Create Goals', description: 'Requires goal_create permission.', tags: ['Finance'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/goals/{goal}', operationId: 'update_goals', summary: 'Update Goals', description: 'Requires goal_edit permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'goal', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/goals/{goal}', operationId: 'delete_goals', summary: 'Delete Goals', description: 'Requires goal_delete permission.', tags: ['Finance'], parameters: [new OA\Parameter(name: 'goal', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/job-types', operationId: 'list_job_types', summary: 'List Job Types', description: 'Requires job_type_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/job-types', operationId: 'create_job_types', summary: 'Create Job Types', description: 'Requires job_type_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/job-types/{job_type}', operationId: 'update_job_types', summary: 'Update Job Types', description: 'Requires job_type_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'job_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/job-types/{job_type}', operationId: 'delete_job_types', summary: 'Delete Job Types', description: 'Requires job_type_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'job_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/subjects', operationId: 'list_subjects', summary: 'List Subjects', description: 'Requires subject_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/subjects', operationId: 'create_subjects', summary: 'Create Subjects', description: 'Requires subject_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/subjects/{subject}', operationId: 'update_subjects', summary: 'Update Subjects', description: 'Requires subject_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'subject', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/subjects/{subject}', operationId: 'delete_subjects', summary: 'Delete Subjects', description: 'Requires subject_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'subject', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/topics', operationId: 'list_topics', summary: 'List Topics', description: 'Requires topic_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/topics', operationId: 'create_topics', summary: 'Create Topics', description: 'Requires topic_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/topics/{topic}', operationId: 'update_topics', summary: 'Update Topics', description: 'Requires topic_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'topic', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/topics/{topic}', operationId: 'delete_topics', summary: 'Delete Topics', description: 'Requires topic_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'topic', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/notes', operationId: 'list_notes', summary: 'List Notes', description: 'Requires note_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/notes', operationId: 'create_notes', summary: 'Create Notes', description: 'Requires note_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/notes/{note}', operationId: 'update_notes', summary: 'Update Notes', description: 'Requires note_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'note', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/notes/{note}', operationId: 'delete_notes', summary: 'Delete Notes', description: 'Requires note_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'note', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/study-goals', operationId: 'list_study_goals', summary: 'List Study Goals', description: 'Requires study_goal_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/study-goals', operationId: 'create_study_goals', summary: 'Create Study Goals', description: 'Requires study_goal_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/study-goals/{study_goal}', operationId: 'update_study_goals', summary: 'Update Study Goals', description: 'Requires study_goal_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'study_goal', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/study-goals/{study_goal}', operationId: 'delete_study_goals', summary: 'Delete Study Goals', description: 'Requires study_goal_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'study_goal', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/exams', operationId: 'list_exams', summary: 'List Exams', description: 'Requires exam_list permission.', tags: ['Study'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/exams', operationId: 'create_exams', summary: 'Create Exams', description: 'Requires exam_create permission.', tags: ['Study'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/exams/{exam}', operationId: 'update_exams', summary: 'Update Exams', description: 'Requires exam_edit permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'exam', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/exams/{exam}', operationId: 'delete_exams', summary: 'Delete Exams', description: 'Requires exam_delete permission.', tags: ['Study'], parameters: [new OA\Parameter(name: 'exam', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/task-types', operationId: 'list_task_types', summary: 'List Task Types', description: 'Requires task_type_list permission.', tags: ['Tasks & Habits'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/task-types', operationId: 'create_task_types', summary: 'Create Task Types', description: 'Requires task_type_create permission.', tags: ['Tasks & Habits'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/task-types/{task_type}', operationId: 'update_task_types', summary: 'Update Task Types', description: 'Requires task_type_edit permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'task_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/task-types/{task_type}', operationId: 'delete_task_types', summary: 'Delete Task Types', description: 'Requires task_type_delete permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'task_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/tasks', operationId: 'list_tasks', summary: 'List Tasks', description: 'Requires task_list permission.', tags: ['Tasks & Habits'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/tasks', operationId: 'create_tasks', summary: 'Create Tasks', description: 'Requires task_create permission.', tags: ['Tasks & Habits'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/tasks/{task}', operationId: 'update_tasks', summary: 'Update Tasks', description: 'Requires task_edit permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/tasks/{task}', operationId: 'delete_tasks', summary: 'Delete Tasks', description: 'Requires task_delete permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'task', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/habit-types', operationId: 'list_habit_types', summary: 'List Habit Types', description: 'Requires habit_type_list permission.', tags: ['Tasks & Habits'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/habit-types', operationId: 'create_habit_types', summary: 'Create Habit Types', description: 'Requires habit_type_create permission.', tags: ['Tasks & Habits'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/habit-types/{habit_type}', operationId: 'update_habit_types', summary: 'Update Habit Types', description: 'Requires habit_type_edit permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'habit_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/habit-types/{habit_type}', operationId: 'delete_habit_types', summary: 'Delete Habit Types', description: 'Requires habit_type_delete permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'habit_type', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/habits', operationId: 'list_habits', summary: 'List Habits', description: 'Requires habit_list permission.', tags: ['Tasks & Habits'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/habits', operationId: 'create_habits', summary: 'Create Habits', description: 'Requires habit_create permission.', tags: ['Tasks & Habits'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/habits/{habit}', operationId: 'update_habits', summary: 'Update Habits', description: 'Requires habit_edit permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'habit', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/habits/{habit}', operationId: 'delete_habits', summary: 'Delete Habits', description: 'Requires habit_delete permission.', tags: ['Tasks & Habits'], parameters: [new OA\Parameter(name: 'habit', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Get(path: '/admin-notices', operationId: 'list_admin_notices', summary: 'List Admin Notices', description: 'Requires notice_list permission.', tags: ['Notices'], responses: [new OA\Response(response: 200, description: 'List retrieved', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Post(path: '/admin-notices', operationId: 'create_admin_notices', summary: 'Create Admin Notices', description: 'Requires notice_create permission.', tags: ['Notices'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Put(path: '/admin-notices/{notice}', operationId: 'update_admin_notices', summary: 'Update Admin Notices', description: 'Requires notice_edit permission.', tags: ['Notices'], parameters: [new OA\Parameter(name: 'notice', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]
#[OA\Delete(path: '/admin-notices/{notice}', operationId: 'delete_admin_notices', summary: 'Delete Admin Notices', description: 'Requires notice_delete permission.', tags: ['Notices'], parameters: [new OA\Parameter(name: 'notice', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse')), new OA\Response(response: 403, description: 'Forbidden')])]

#[OA\Get(path: '/expenses/{expense}/image', operationId: 'expenseImage', summary: 'Get expense image', tags: ['Finance'], parameters: [new OA\Parameter(name: 'expense', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Image file', content: new OA\MediaType(mediaType: 'image/*', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/savings/{saving}/image', operationId: 'savingImage', summary: 'Get saving image', tags: ['Finance'], parameters: [new OA\Parameter(name: 'saving', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Image file', content: new OA\MediaType(mediaType: 'image/*', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/withdraws/{withdraw}/image', operationId: 'withdrawImage', summary: 'Get withdraw image', tags: ['Finance'], parameters: [new OA\Parameter(name: 'withdraw', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Image file', content: new OA\MediaType(mediaType: 'image/*', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/notes/{note}/file', operationId: 'noteFile', summary: 'Get note file', tags: ['Study'], parameters: [
    new OA\Parameter(name: 'note', in: 'path', required: true, schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'path', in: 'query', required: true, schema: new OA\Schema(type: 'string')),
], responses: [new OA\Response(response: 200, description: 'File', content: new OA\MediaType(mediaType: 'application/octet-stream', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/exams/{exam}/file', operationId: 'examFile', summary: 'Get exam file', tags: ['Study'], parameters: [
    new OA\Parameter(name: 'exam', in: 'path', required: true, schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'path', in: 'query', required: true, schema: new OA\Schema(type: 'string')),
], responses: [new OA\Response(response: 200, description: 'File', content: new OA\MediaType(mediaType: 'application/octet-stream', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/study-goals/export-pdf', operationId: 'studyGoalsExportPdf', summary: 'Export study goals as PDF', tags: ['Study'], parameters: [
    new OA\Parameter(name: 'date_from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
    new OA\Parameter(name: 'date_to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
    new OA\Parameter(name: 'user_id', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'subject_id', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'topic_id', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'job_id', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'goal_status', in: 'query', schema: new OA\Schema(type: 'string', enum: ['pending', 'doing', 'completed'])),
], responses: [new OA\Response(response: 200, description: 'PDF file', content: new OA\MediaType(mediaType: 'application/pdf', schema: new OA\Schema(type: 'string', format: 'binary')))])]
#[OA\Get(path: '/exams/export-pdf', operationId: 'examsExportPdf', summary: 'Export exams as PDF', tags: ['Study'], parameters: [
    new OA\Parameter(name: 'date_from', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
    new OA\Parameter(name: 'date_to', in: 'query', schema: new OA\Schema(type: 'string', format: 'date')),
    new OA\Parameter(name: 'job_type_id', in: 'query', schema: new OA\Schema(type: 'integer')),
    new OA\Parameter(name: 'exam_status', in: 'query', schema: new OA\Schema(type: 'string')),
], responses: [new OA\Response(response: 200, description: 'PDF file', content: new OA\MediaType(mediaType: 'application/pdf', schema: new OA\Schema(type: 'string', format: 'binary')))])]
class ResourcePaths
{
}
