<?php

namespace App\OpenApi\Paths;

use OpenApi\Attributes as OA;

#[OA\Get(path: '/users', operationId: 'listUsers', summary: 'List users', tags: ['Users & Access'], responses: [new OA\Response(response: 200, description: 'Users and role options', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Post(path: '/users', operationId: 'createUser', summary: 'Create user', tags: ['Users & Access'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Get(path: '/users/{user}', operationId: 'showUser', summary: 'Get user', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'User details', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Put(path: '/users/{user}', operationId: 'updateUser', summary: 'Update user', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\MediaType(mediaType: 'multipart/form-data', schema: new OA\Schema(type: 'object'))), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Post(path: '/users/{user}/status', operationId: 'updateUserStatus', summary: 'Update user status', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(required: ['status'], properties: [new OA\Property(property: 'status', type: 'integer', enum: [0, 1])])), responses: [new OA\Response(response: 200, description: 'Status updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Delete(path: '/users/{user}', operationId: 'deleteUser', summary: 'Delete user', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'user', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Get(path: '/roles', operationId: 'listRoles', summary: 'List roles', tags: ['Users & Access'], responses: [new OA\Response(response: 200, description: 'Roles and permissions', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Post(path: '/roles', operationId: 'createRole', summary: 'Create role', tags: ['Users & Access'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Put(path: '/roles/{role}', operationId: 'updateRole', summary: 'Update role', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Delete(path: '/roles/{role}', operationId: 'deleteRole', summary: 'Delete role', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'role', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Get(path: '/permissions', operationId: 'listPermissions', summary: 'List permissions', tags: ['Users & Access'], responses: [new OA\Response(response: 200, description: 'Permissions list', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Post(path: '/permissions', operationId: 'createPermission', summary: 'Create permission', tags: ['Users & Access'], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 201, description: 'Created', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Put(path: '/permissions/{permission}', operationId: 'updatePermission', summary: 'Update permission', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'permission', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], requestBody: new OA\RequestBody(content: new OA\JsonContent(type: 'object')), responses: [new OA\Response(response: 200, description: 'Updated', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
#[OA\Delete(path: '/permissions/{permission}', operationId: 'deletePermission', summary: 'Delete permission', tags: ['Users & Access'], parameters: [new OA\Parameter(name: 'permission', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))], responses: [new OA\Response(response: 200, description: 'Deleted', content: new OA\JsonContent(ref: '#/components/schemas/ApiSuccessResponse'))])]
class UserPaths
{
}
